# Generated by Django 5.2.8 on 2026-02-09 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('requested_by', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=150)),
                ('date_requested', models.DateField()),
                ('time_requested', models.TimeField()),
                ('am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('description', models.TextField()),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('brand_model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=50, unique=True)),
                ('date_request', models.DateField()),
                ('time_request', models.TimeField()),
                ('am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('request_complaint', models.TextField()),
                ('equipment', models.CharField(max_length=100)),
                ('brand_model', models.CharField(max_length=100)),
                ('division_section', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('action_taken', models.TextField()),
                ('action_officer', models.CharField(max_length=100)),
                ('job_confirmation', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing_queue.ticket')),
            ],
        ),
    ]
