# Generated by Django 5.2.8 on 2026-02-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0003_alter_auditlog_user_alter_ticket_brand_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Check if this is an urgent request', verbose_name='Urgent Request'),
        ),
    ]
