# Generated by Django 5.2.8 on 2026-02-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0004_ticket_is_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_urgent',
        ),
    ]
