# Generated by Django 5.2.8 on 2026-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0005_remove_ticket_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
