# Generated by Django 5.2.8 on 2026-02-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Check if this request needs immediate attention', verbose_name='Urgent Request'),
        ),
    ]
