# Generated by Django 5.2.8 on 2026-02-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0008_ticket_assisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('assisting', 'Assisting'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
