# Generated by Django 5.2.8 on 2026-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0011_ticket_accepted_at_ticket_assisted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was moved to archive', null=True),
        ),
    ]
