# Generated by Django 5.2.8 on 2026-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0012_ticket_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=50, unique=True)),
                ('requested_by', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=100)),
                ('division_section', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archived Ticket',
                'verbose_name_plural': 'Archived Tickets',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='archived_at',
        ),
    ]
