# Generated by Django 5.2.8 on 2026-02-23 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0013_archivedticket_remove_ticket_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedticket',
            name='division_section',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='brand_model',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='division_section',
        ),
        migrations.AddField(
            model_name='ticket',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='brand_other',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department_division',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Department / Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='model_other',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section_unit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Section / Unit'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent Request'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requested_by',
            field=models.CharField(max_length=150),
        ),
    ]
