# Generated by Django 5.2.8 on 2026-02-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0014_remove_archivedticket_division_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='brand_other',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='model_other',
        ),
    ]
