# Generated by Django 5.2.8 on 2026-02-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0015_remove_ticket_brand_other_remove_ticket_model_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='itrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
