# Generated by Django 5.2.8 on 2026-02-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0016_itrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_manually_modified',
            field=models.BooleanField(default=False),
        ),
    ]
