# Generated by Django 5.2.8 on 2026-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0017_remove_itrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedticket',
            name='division',
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='department_division',
            field=models.CharField(blank=True, default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='section_unit',
            field=models.CharField(blank=True, default='N/A', max_length=150),
        ),
    ]
