# Generated by Django 5.2.8 on 2026-02-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0018_remove_archivedticket_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedticket',
            name='division',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
