# Generated by Django 5.2.8 on 2026-02-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0019_archivedticket_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedticket',
            name='department_division',
        ),
        migrations.RemoveField(
            model_name='archivedticket',
            name='section_unit',
        ),
    ]
