# Generated by Django 5.2.8 on 2026-02-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0020_remove_archivedticket_department_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedticket',
            name='division',
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='department_division',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='section_unit',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
