# Generated by Django 5.2.8 on 2026-02-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0021_remove_archivedticket_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedticket',
            name='department_division',
        ),
        migrations.RemoveField(
            model_name='archivedticket',
            name='section_unit',
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='division',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
