# Generated by Django 5.2.8 on 2026-02-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0026_auditlog_user'),
    ]

    operations = [
    ]
