# Generated by Django 5.2.8 on 2026-02-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0028_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
