# Generated by Django 5.2.8 on 2026-02-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0030_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
