# Generated by Django 5.2.8 on 2026-02-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0036_staffprofile_delete_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
