# Generated by Django 5.2.8 on 2026-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0038_alter_staffprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
