# Generated by Django 5.2.8 on 2026-03-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0040_auditlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing_queue.ticket'),
        ),
    ]
