# Generated by Django 5.2.8 on 2026-03-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0041_auditlog_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auditlog',
            unique_together={('ticket', 'action')},
        ),
    ]
