# Generated by Django 5.2.8 on 2026-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0042_alter_auditlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='division_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
