# Generated by Django 5.2.8 on 2026-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0043_ticket_division_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedticket',
            name='assisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='assisted_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='archivedticket',
            name='completed_by',
            field=models.CharField(default='ICT Personnel', max_length=150),
            preserve_default=False,
        ),
    ]
