# Generated by Django 5.2.8 on 2026-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0044_archivedticket_assisted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedticket',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
