# Generated by Django 5.2.8 on 2026-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0045_archivedticket_action_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTakenOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
