# Generated by Django 5.2.8 on 2026-04-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0048_ticket_assigned_at_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
    ]
