# Generated by Django 5.2.8 on 2026-04-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_queue', '0050_ticketfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('assisting', 'Assisting'), ('completed', 'Completed'), ('follow_up_pending', 'Follow-Up Pending')], default='pending', max_length=20),
        ),
    ]
